site_name: LFADS Run Manager
site_description: Documentation of LFADS Run Manager for Matlab
site_author: Daniel J. O'Shea

repo_name: 'djoshea/lfads-run-manager'
repo_url: 'https://github.com/djoshea/lfads-run-manager'

theme:
  name: material
  custom_dir: docs/theme/
  palette:
    primary: 'red'
    accent: 'red'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/djoshea'
    - type: 'twitter'
      link: 'https://twitter.com/djoshea'

markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.def_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - smarty
  - toc(permalink=true)

pages:
  - Overview: index.md
  - Installation: install.md
  - Matlab Classes and Packages: matlab.md
  - Key Concepts: concepts.md
  - Interfacing with your Datasets : interfacing.md
  - Preparing for LFADS: preparing.md
  - File Organization: files.md
  - Multisession Stitched Models: multisession.md
  - Running LFADS: running.md
  - Analyzing LFADS Posterior Means: analysis.md
  - Loading the Model Trained Parameters: trained_params.md

copyright: 'Copyright &copy; 2017 &mdash; Daniel J. O&#39;Shea'

google_analytics_code: 'UA-322693-7'
